sas/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("events.urls")),
    path("case/", include("case_details.urls")),
    path("driver/", include("driver.urls")),
    path("care/", include("customer_care.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

case_details/models.py
from django.db import models
from django.contrib.auth.models import User

STATUSES = [
    (0, "Open"),
    (1, "Closed"),
]


# cc = customer care
class Cc_person(models.Model):
    cc_id = models.BigAutoField(primary_key="True", auto_created="True")
    cc_gov_id = models.CharField(max_length=50, unique=True, null=False)
    phone_number = models.CharField(max_length=15, unique=True, null=False)
    photo = models.ImageField(null=True, upload_to="cc_photos/")

    user_cc = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_cc")

    class Meta:
        db_table = "Customer Care Person"

    def _str_(self):
        return self.user.username


class Driver(models.Model):
    license_number = models.CharField(max_length=50, unique=True, null=False)
    # phone_number = models.CharField(max_length=15, unique=True, null=False)
    driver_photo = models.ImageField(null=True, upload_to="driver_photos/")
    user_driver = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="user_driver"
    )
    case_status = models.IntegerField(choices=STATUSES, default=0)
    current_location = models.CharField(max_length=255, null=True, blank=True)
    is_tracking = models.BooleanField(default=False)
    amb_con = models.BooleanField(default=0);

    class Meta:
        db_table = "Driver"

    def __str__(self):
        return self.user_driver.username


class Ambulance(models.Model):
    AMBULANCE_SIZES = [
        ("B", "Big"),
        ("M", "Medium"),
    ]

    ambulance_id = models.BigAutoField(primary_key=True, auto_created=True)
    ambulance_number = models.CharField(max_length=20, unique=True, null=False)
    ambulance_size = models.CharField(max_length=1, choices=AMBULANCE_SIZES, null=False)
    ambulance_model = models.CharField(max_length=50, null=False)
    ambulance_photo = models.ImageField(null=True, upload_to="ambulance_photos/")
    hospital = models.ForeignKey("Hospital", on_delete=models.CASCADE)
    driver_1 = models.ForeignKey(
        "Driver", related_name="primary_driver", on_delete=models.CASCADE
    )
    driver_1_con = models.BooleanField(default=1);
    driver_2 = models.ForeignKey(
        "Driver", related_name="secondary_driver", on_delete=models.SET_NULL, null=True
    )
    bystander_1 = models.CharField(max_length=50, null="False")
    bystander_2 = models.CharField(max_length=50, null="False")
    bystander_3 = models.CharField(max_length=50, null="True")
    bystander_4 = models.CharField(max_length=50, null="True")

    class Meta:
        db_table = "Ambulance"

    def __str__(self):
        return self.ambulance_number


class Hospital(models.Model):
    hospital_id = models.BigAutoField(primary_key=True, auto_created=True)
    name = models.CharField(max_length=200, unique=True, null=False)
    address = models.CharField(max_length=1500, null=True)

    class Meta:
        db_table = "Hospital"

    def __str__(self):
        return self.name


from django.db import models
from django.contrib.auth.models import User
import datetime


class Case(models.Model):
    ACCIDENT_TYPES = [
        ("VEH", "Vehicle Collision"),
        ("FAL", "Fall"),
        ("BUR", "Burn"),
        ("CUT", "Laceration"),
        ("OTH", "Other"),
    ]

    SEVERITY_LEVELS = [
        ("CRT", "Critical"),
        ("SR", "Serious"),
        ("MD", "Mild"),
        ("MIN", "Minor"),
    ]

    case_id = models.BigAutoField(primary_key=True, auto_created=True)
    Patient_name = models.CharField(max_length=35)
    # poc = point of contact
    poc = models.CharField(max_length=35)
    accident_type = models.CharField(
        max_length=3, choices=ACCIDENT_TYPES, default="OTH"
    )
    patient_severity = models.CharField(
        max_length=3, choices=SEVERITY_LEVELS, default="MIN"
    )
    location = models.CharField(max_length=255)
    time_date = models.DateTimeField(default=datetime.datetime.now)
    status = models.IntegerField(choices=STATUSES, default=0)

    ambulance = models.ForeignKey("Ambulance", on_delete=models.SET_NULL, null=True)
    assigned_cc_person = models.ForeignKey(
        "cc_person", on_delete=models.SET_NULL, null=True
    )

    # Additional details
    description = models.TextField(null=True, blank=True)
    first_responder_notes = models.TextField(null=True, blank=True)

    class Meta:
        db_table = "Case"

    def __str__(self):
        return f"Case {self.case_id}"

templates/case/case.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Dashboard | Care</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <script>
        function initMap() {
            // Initialize the map
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 12,
                center: { lat: {{ location_lat }}, lng: {{ location_lng }} }
            });

            var markers = [
                { 
                    lat: {{ location_lat }},
                    lng: {{ location_lng }},
                    icon: null 
                },
                { 
                    lat: {{ amb_location_lat }},
                    lng: {{ amb_location_lng }},
                    icon: "{% static 'assets/img/ambulance.png' %}"
                }
            ];

        markers.forEach(function (location) {
            new google.maps.Marker({
                position: location,
                map: map,
                icon: location.icon
            });
        });
        }
    </script>
    <!-- Load the Google Maps JavaScript API asynchronously -->
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=< use your api key here >&callback=initMap"></script>
    <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

    <main>
        <div class="container">

            <section class="section profile">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="d-flex justify-content-center py-4">
                            <span class="card-title pb-0 fs-4 d-lg-block"><b>Case ID : {{ case.case_id }}</b></span>
                        </div><!-- End Logo -->


                        <div class="card">
                            <div class="card-body">
                                <br>
                                <br>
                                <div id="map" style="width: 100%; height: 400px;"></div>
                                <h3>Case Details</h3>
                                <p>Patient Name: {{ case.Patient_name }}</p>
                                <p>Point of Contact: {{ case.poc }}</p>
                                <p>Accident Type: {{ case.get_accident_type_display }}</p>
                                <p>Patient Severity: {{ case.get_patient_severity_display }}</p>
                                <p>Location: {{ case.location }}</p>
                                <p>Time and Date: {{ case.time_date }}</p>
                                <p>Status: {{ case.get_status_display }}</p>
                                <p>Ambulance: {{ case.ambulance.ambulance_number }}</p>
                                <p>Assigned CC Person: {{ case.assigned_cc_person.user_cc.username }}</p>
                            </div>
                        </div>

                        <div class="credits">
                        </div>
                    </div>

            </section>

        </div>
    </main><!-- End #main -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/quill/quill.js' %}"></script>
    <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

templates/case/case_id.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>ID | Care</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <!-- =======================================================
  * Template Name: NiceAdmin
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Updated: Apr 20 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

    <main>
        <div class="container">

            <section
                class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

                            <div class="d-flex justify-content-center py-4">
                                <span class="card-title pb-0 fs-4 d-lg-block"><b>SAS Case ID</b></span>
                            </div><!-- End Logo -->

                            <div class="card mb-3">

                                <div class="card-body">

                                    <div class="pt-4 pb-2">
                                        <h5 class="card-title text-center pb-0 fs-4">Enter your case id here</h5>
                                    </div>
                                    <br><br>

                                    <form action="#" method="post" enctype="multipart/form-data"
                                        class="row g-3 needs-validation" novalidate>
                                        {% csrf_token %}
                                        <div class="col-12">
                                            <label for="yourUsername" class="form-label">ID</label>
                                            <div class="input-group has-validation">
                                                <!-- <span class="input-group-text" id="inputGroupPrepend">@</span> -->
                                                <input type="text" name="case_unique_id" class="form-control" id="yourUsername"
                                                    required>
                                                <div class="invalid-feedback">Please enter your Case ID.</div>
                                            </div>
                                        </div>


                                        <div class="col-12">
                                            <button class="btn btn-primary w-100" type="submit">Open</button>
                                        </div>
                                    </form>

                                </div>
                            </div>

                            <div class="credits">
                            </div>
                        </div>
                    </div>

            </section>

        </div>
    </main><!-- End #main -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/quill/quill.js' %}"></script>
    <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>